# Controls when the workflow will run
on:
  # Allows you to run this workflow manually target the Actions tab
  workflow_dispatch:

name: Build Windows
jobs:
  build:
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
    runs-on: windows-latest    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Msys
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            base-devel
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-SDL             
            mingw-w64-${{matrix.env}}-SDL_ttf
            mingw-w64-${{matrix.env}}-SDL_image
            mingw-w64-${{matrix.env}}-SDL_mixer
            mingw-w64-${{matrix.env}}-SDL_gfx
            mingw-w64-${{matrix.env}}-make
            mingw-w64-${{matrix.env}}-harfbuzz
            mingw-w64-${{matrix.env}}-freetype
            mingw-w64-${{matrix.env}}-libwebp
            mingw-w64-${{matrix.env}}-libtiff
            mingw-w64-${{matrix.env}}-libmikmod
      - name: Build Game
        shell: msys2 {0}
        run: |
          make
      - name: Copy Game And Assets
        shell: msys2 {0}
        run: |
          mkdir ./Release
          mkdir ./Release/Blips
          cp blips.exe ./Release/Blips/ || :
          cp -R ./fonts ./Release/Blips/ || :
          cp -R ./graphics ./Release/Blips/ || :
          cp -R ./levelpacks ./Release/Blips/ || :
          cp -R ./music ./Release/Blips/ || :
          cp -R ./sound ./Release/Blips/ || :
          cp ./README.md ./Release/Blips/ || :
          cp ./LICENSE ./Release/Blips/ || :
      - name: Copy dll libraries
        shell: msys2 {0}
        run: |
          cp /${{matrix.sys}}/bin/libbrotli*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libbz*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libdeflate*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libdeflate*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libfreetype*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libgcc*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libglib*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libgraphite*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libharfbuzz*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libiconv*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libintl*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libjbig*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libjpeg*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libLerc*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/liblzma*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libmikm*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libmad*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libogg*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libopenal*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libpcre*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libpng*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libstdc*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libtiff*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libwebp*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libzstd*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/zlib*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libSDL*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/SDL*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libsharpyuv*.dll ./Release/Blips/ || :
          cp /${{matrix.sys}}/bin/libwinpthread*.dll ./Release/Blips/ || :
      - name: Store build
        uses: actions/upload-artifact@v3
        with:
          name: Blips ${{ matrix.env }}
          path: ./Release/
